apiVersion: gateway.networking.k8s.io/v1
kind: HttpRoute
metadata:
  name: keycloak
spec:
  parentRefs:
  - name: kgateway
  rules:
  - matches:
      - path:
          type: PathPrefix
          value: /
    backendRefs:
      - name: keycloak
        port: 8080